---
prowlarr_memory: 1g
prowlarr_network_mode: container:gluetun
prowlarr_user_id: "{{ homeserver_user_id }}"
prowlarr_group_id: "{{ homeserver_group_id }}"
prowlarr_config_directory: "{{ homeserver_docker_home }}/prowlarr/config"
prowlarr_domain: "{{ homeserver_domain }}"
