---
nextdns_memory: 1g
nextdns_profile: "{% if nextdns_configuration_id is defined %}-profile={{ nextdns_configuration_id }}{% endif %}"
nextdns_command: run {{ nextdns_profile }} -listen=:53 -report-client-info
