---
seerr_memory: 1g
seerr_port: 5055
seerr_user_id: "{{ homeserver_user_id }}"
seerr_group_id: "{{ homeserver_group_id }}"
seerr_config_directory: "{{ homeserver_docker_home }}/seerr/config"
seerr_domain: "{{ homeserver_domain }}"
