---
- name: Create Seerr directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ seerr_config_directory }}"
- name: Start Seerr container
  community.docker.docker_container:
    name: seerr
    image: seerr/seerr:latest
    pull: true
    ports:
      - "{{ seerr_port }}:5055"
    env:
      LOG_LEVEL: info
    restart_policy: unless-stopped
    memory: "{{ seerr_memory }}"
    user: "{{ seerr_user_id }}:{{ seerr_group_id }}"
    volumes:
      - "{{ seerr_config_directory }}:/app/config:rw"
    labels:
      traefik.enable: "{{ true | string }}"
      traefik.http.routers.seerr.rule: Host(`seerr.{{ seerr_domain }}`)
      traefik.http.routers.seerr.tls: "true"
      traefik.http.routers.seerr.tls.certresolver: letsencrypt
      traefik.http.routers.seerr.tls.domains[0].main: "{{ seerr_domain }}"
      traefik.http.routers.seerr.tls.domains[0].sans: "*.{{ seerr_domain }}"
      traefik.http.services.seerr.loadbalancer.server.port: "5055"
